config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    :controllers => { :registrations => 'users/registrations' }
  root to: "toppages#index"
  resources :books , only: [:index, :create, :new, :destroy]
  resources :genres , only: [:new, :create] 
  resources :trashes , only: [:index]
  resources :read_book_logs, only: :index

  post 'read_book_log/:id' => 'read_book_logs#create', 
    as: 'create_read_book_log'
  get 'read_book_log' => 'read_book_logs#genre_ranking', 
    as: 'index_genre_ranking'
  get 'read_book_log_graph' => 'read_book_logs#graph', 
    as: 'index_graph'
  post 'books/:id' => 'books#trash', 
    as: 'trash_book'  
  get 'books_search' => 'books#search', 
    as: 'books_search'
  get 'book_trashes_box' => 'books#trashes_box',
    as: 'trashes_box'
  post 'book_trashes_restore/:id' => 'books#recover_from_trashbox', 
    as: 'trash_restore'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :book_subject, presence: true
  belongs_to :user
  belongs_to :genre
  has_many :read_book_logs, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre_name, presence: true
  belongs_to :user
  has_many :books
  has_many :read_book_logs
end

app/models/read_book_log.rb
class ReadBookLog < ApplicationRecord
  validates :log, presence: true
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImageUploader

  belongs_to :genre, optional: true, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :read_book_logs, dependent: :destroy

  validates :nickname, presence: true, length: { maximum: 20 }

  
  def soft_delete  
    update_attribute(:deleted_at, Time.current)  
  end

  def active_for_authentication?  
    super && !deleted_at  
  end  

  def inactive_message   
    !deleted_at ? super : :deleted_account  
  end 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_account_update_parammeters, if: :devise_controller?


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:image])
  end

  def configure_account_update_parammeters
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :image])
   end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, 
    only: [:index, :new, :create, :destroy, :trash, :trashes_box, :recover_from_trashbox]

  def index
    @books = Book.where(user_id: current_user.id,is_deleted: false)
    @book_image_url = []
    @books.each do |book|
      book_data = RakutenWebService::Books::Book.search(title: book.book_subject)
      if book_data.count == 0
        @book_image_url << nil
      else
        book_data.each_with_index do |book_url,i|
          if i == 0 
            book_url_a_data = book_url.large_image_url
            @book_image_url << book_url_a_data
          end
        end
      end
    end
  end

  def new
    @book = Book.new
    if params[:keyword]
      @books = RakutenWebService::Books::Book.search(title: params[:keyword])
      render :new
    end
  end

  def create
    binding.pry
    @book = Book.new(book_params)
    if @book.save
      flash[:success_book_registration] = CREATE_BOOK_SUCCESS
      redirect_to root_path
    else  
      flash.now[:error_book] = CREATE_BOOK_VALIDATION_ERROR
      render :new
    end
  end

  def search
    if params[:keyword]
      @books = RakutenWebService::Books::Book.search(title: params[:keyword])
    end
  end



  def destroy
    ActiveRecord::Base.transaction do
      book = Book.find(params[:id])
      if book.valid?
        book.destroy
        flash[:success_book_destroy] = BOOK_DESTROY_SUCCESS
        redirect_to root_path
      else
        flash.now[:error_book] = BOOK_INVALID_ERROR
        render :destroy
      end
    end


  end

  def trash
    ActiveRecord::Base.transaction do
      book = Book.find(params[:id])
      if book.valid?
        book.update(is_deleted: true)
        flash[:success_book_trash] = BOOK_TRUSH_SUCCESS
        redirect_to root_path
      else
        flash.now[:error_book] = BOOK_INVALID_ERROR
        render :trash
      end
    end
  end

  def trashes_box
    @books = Book.where(user_id: current_user.id, is_deleted: true)
  end

  def recover_from_trashbox
    ActiveRecord::Base.transaction do      
      book = Book.find(params[:id])
      if book.valid?
        book.update(is_deleted: false)
        redirect_to root_path
      else
        flash.now[:error_book] = BOOK_INVALID_ERROR
        render :recover_from_trashbox
      end
    end
  end

  private

  def book_params
    params
    .require(:book)
    .permit(:book_subject,:genre_id,:is_deleted)
    .merge(user_id: current_user.id)
  end
  
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success_genre] = CREATE_GENRE_SUCCESS
      redirect_to root_path
    else
      flash.now[:error_genre] = CREATE_GENRE_VALIDATION_ERROR
      render :new
    end
  end

  private
  def genre_params
    params
    .require(:genre)
    .permit(:genre_name)
    .merge(user_id: current_user.id)
  end

end

app/controllers/read_book_logs_controller.rb
class ReadBookLogsController < ApplicationController
  require "date"
  before_action :authenticate_user!, only: [:create, :index, :genre_ranking, :graph]

  DEFAULT_BOOK_LOG_NUM = 5
  DEFAULT_GENRE_RANK_NUM = 5
  BOOL_LOG_PERIOD = 30


  def create
    ReadBookLog.create(
      user_id: current_user.id, 
      book_id: params[:id], 
      log: Date.today
    )
    redirect_to books_path
  end

  def index
    @read_book_logs = Book
    .joins(:read_book_logs)
    .joins(:genre)
    .where(user_id: current_user.id)
    .group("books.book_subject")
    .group("genres.genre_name")
    .order('count_all DESC')
    .count
    .first(DEFAULT_BOOK_LOG_NUM)
  end

  def genre_ranking
    @read_book_logs = Book
    .joins(:read_book_logs)
    .joins(:genre)
    .where(user_id: current_user.id)
    .group("genres.genre_name")
    .order('count_all DESC')
    .count
    .first(DEFAULT_GENRE_RANK_NUM)
  end

  def graph
    @datas = ReadBookLog
    .where(user_id: current_user.id)
    .select(:log)
    .group("read_book_logs.log")
    .count
    .first(BOOL_LOG_PERIOD)

  end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
end

app/views/books/_book_registration_page.erb
<div class="book_registration_box">
  <h2 class="book_registration_name_top">新しい本の登録</h2>
  <%= form_with url: new_book_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, class: "search_form" %>
    <%= f.submit '表示させたい表紙を検索', class: "search_btn" %>
      <% if @books.present? %>
        <%= render 'search_result' %>
      <% end %>
  <% end %>
  <%= form_with(model: @book, local: true) do |form| %>
    <div class="book_name_registration_box">
      <%= form.text_field :book_subject ,
        class: "book_input_size", 
        placeholder: "本のタイトル(検索をし、表示させたい表紙のタイトルを入力してください。)" 
      %>
    </div>
    <div class="book_genre_registration_box">
      <%= form.select :genre_id, 
        Genre
        .where(user_id: current_user.id)
        .map{ |genre| [genre.genre_name, genre.id]}, 
        { include_blank: 'ジャンルを選んでください。希望のジャンルがない場合は、Topページから新規ジャンルの登録をしてください。'}, 
        {class: "select_tab"}
      %>
    </div>
    <div class="book_name_registration_submit">
      <%= form.submit  "登録" , class: "book_name_submit"%>
    </div>
  <% end %>
</div>

app/views/books/_headder.html.erb
<div class="headder_left_content">
  <%= link_to "YOMEBA", root_path, class: "headder_logo" %>
</div>
<div class="headder_right_content">
  <% if user_signed_in? %>
    <div class="logout">
      <%= link_to "ログアウト", 
        destroy_user_session_path, 
        method: :delete, 
        class: "headder_logout_button" 
      %>
    </div>
    <div class="user_icon">
      <% if current_user.image.presence %>
        <a href="/users/edit">
          <img src=<%= current_user.image %> 
          alt="#{current_user.nickname}さんのプロフィール画像" 
          class="user_icon">
        </a>
      <% else %>
        <%= link_to image_tag("/images/animal_stand_penguin.png", 
          :alt => "#{current_user.nickname}さんのプロフィール画像",
          class: 'user_icon' ), 
          edit_user_registration_path 
        %>
      <% end %>
    </div>
  <% else %>
      <div class="login">
        <%= link_to "ログイン", 
          new_user_session_path, 
          class: "headder_login_button" 
        %>
      </div>
      <div class="sign_up">
        <%= link_to "サインアップ",
          new_user_registration_path,
          class: "sign_up_button" 
        %>
      </div>
  <% end %>
</div>

app/views/books/_main_book_list.html.erb
<div class="book_contents_line">
  <ul class="item_lists">
    <% if @books.length > 0 %>
      <% @books.each_with_index do |book,i| %>
        <li class="item_list">
          <div class="book_content">
            <div class="book_image">
              <% if @book_image_url[i].present? %>
                <%= image_tag @book_image_url[i], class: "book_original_image"%>
              <% else %>
                <img src="/images/book_cover.png" alt="絵本の表紙" title="絵本の表紙">
                <div class="book_subject">
                  <%= book.book_subject %>
                </div>
              <% end %>
              <div class="book_destroy">
                <%= link_to '完全削除', book_path(book.id), method: :delete %>
                <%= link_to 'ゴミ箱に移動', trash_book_path(book.id), method: :post %>
              </div>
            </div>
            <div class="book_count_space">
              <div class="count_button_plus">
                <%= link_to image_tag("/images/plus.png", class: 'count_button', alt: "プラスボタン" )  , 
                  create_read_book_log_path(book.id), 
                  method: :POST 
                %>
              </div>
              <div class="book_count_result">
                <h1 class="count_result"><%= book.read_book_logs.count %></h1>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    <% else %>
      <div class="book_content_first_time">
        <div class="book_image">
          <img src="/images/book_cover.png" 
            alt="絵本の表紙" 
            title="絵本の表紙"
          >
          <div class="book_subject">
            <%= "1冊目の本を" %><br>
            <%= "登録しよう！" %>
          </div>
        </div>
        <div class="book_count_space">
          <div class="count_button_plus">
            <img src="/images/plus.png" 
              alt="プラスボタン" 
              title="プラスボタン" 
              class="count_button"
            >
          </div>
          <div class="book_count_result">
            <h1 class="count_result">0回</h1>
          </div>
        </div>
      </div>
    <% end %>
  </ul>
</div>

app/views/books/_search_result.html.erb
<div class="image_result">
  <% @books.each do |book,index| %>
      <div class="book_images_result">
        <%= image_tag book.large_image_url,class: "book_images" %>
        <div class= "book_image_title">
          <%= "#{book.title}" %>
        </div>
      </div>
  <% end %>
</div>

app/views/books/_trash_book_list.html.erb
<div class="trash_book_contents_line">
  <ul class="item_lists">
    <% if @books.length > 0 %>
      <% @books.each do |book| %>
        <li class="item_list">
          <div class="book_content">
            <div class="book_image">
              <img src="/images/book_cover.png" alt="絵本の表紙" title="絵本の表紙">
              <div class="book_subject">
                <%= book.book_subject %>
              </div>
              <div class="book_destroy">
                <%= link_to '復活', trash_restore_path(book.id), method: :post %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    <% else %>
      <div class="book_content_first_time">
        <div class="book_image">
          <img src="/images/book_cover.png" alt="絵本の表紙" title="絵本の表紙">
          <div class="book_subject">
            <%= "ゴミ箱の中に" %><br>
            <%= "本はありません" %>
          </div>
        </div>
      </div>
    <% end %>
  </ul>
</div>

app/views/books/index.html.erb
<div class="wrapper">
  <div class="headder">
    <%= render "headder" %>
  </div>
  <div class="book_list">
    <%= render "main_book_list" %>
  </div>
</div>

app/views/books/new.html.erb
<div class="wrapper">
  <div class="headder">
    <%= render "headder" %>
  </div>
  <div class="book_registration_page">
    <%= render "book_registration_page" %>
  </div>
</div>

app/views/books/trashes_box.html.erb
<div class="wrapper">
  <div class="headder">
    <%= render "books/headder" %>
  </div>
  <div class="trash_book_list">
    <%= render "trash_book_list" %>
  </div>
</div>

app/views/genres/new.html.erb
<div class="headder">
  <%= render "books/headder" %>
</div>

<div class="genre_registration_space">
  <div class="genre_registration_box">
    <h2 class="genre_registration_name_top">本のジャンル登録</h2>
    <%= form_with(model: @genre, local: true) do |form| %>
      <div class="genre_name_registration_box">
        <%= form.text_field :genre_name , 
          class: "genre_input_size", 
          placeholder: "本のジャンル名" 
        %>
      </div>
      <div class="genre_name_registration_submit">
        <%= form.submit  "登録" , class: "genre_name_submit"%>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YOMEBA</title>
    <meta content="絵本は、どのように選んでいますか？人気ランキング？
      親の趣向？インフルエンサーの提案？どれも、素晴らしいと思います。ただ、お子様の示す興味は、1人1人違います。
      このアプリで、お子様の興味分野を調べ、次に読む絵本を選ぶ判断材料にしてくださると嬉しいです！" 
      name="description"
    >
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" 
      type="text/css" 
      href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css"
    >
    <%= stylesheet_link_tag 'application', 
      media: 'all', 
      'data-turbolinks-track': 'reload' 
    %>
    <%= javascript_pack_tag    'application' %>
  </head>

  <body>
    <div class="notification">
      <% flash.each do |message_type, message| %>
        <%= message %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/read_book_logs/_book_ranking_page.html.erb
<div class="book_ranking_space">
  <div class="book_ranking_space_top">
    読んだ絵本の回数ランキング！！！
  </div>
  <div class="book_ranking_content">
    <div class="book_ranking_content_box_topic">
      <div class="book_ranking_content_topic">
        <%= '順位' %>
      </div>
      <div class="book_ranking_content_detail_topic">
        <%= '本のタイトル' %>
      </div>
      <div class="book_ranking_content_detail_topic">
        <%= 'ジャンル名' %>
      </div>
      <div class="book_ranking_content_detail_topic">
        <%= '読んだ回数' %>
      </div>
    </div>
    <% @read_book_logs.each_with_index do |book,i| %>
      <div class="book_ranking_content_box">
        <div class="book_ranking_content_rank">
          <%= "#{i+1}位"%>
        </div>
        <div class="book_ranking_content_detail">
          <%= book[0][0] %>
        </div>
        <div class="book_ranking_content_detail">
          <%= book[0][1] %>
        </div>
        <div class="book_ranking_content_detail">
          <%= "#{book[1]}回" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/read_book_logs/_genre_ranking_page.html.erb
<div class="genre_ranking_space">
  <div class="genre_ranking_space_top">
    読んだ絵本のジャンルランキング！！！
  </div>
  <div class="genre_ranking_content">
    <div class="genre_ranking_content_box_topic">
      <div class="genre_ranking_content_topic">
        <%= '順位' %>
      </div>
      <div class="genre_ranking_content_detail_topic">
        <%= 'ジャンル名' %>
      </div>
      <div class="genre_ranking_content_detail_topic">
        <%= '読んだ回数' %>
      </div>
    </div>
    <% @read_book_logs.each_with_index do |book,i| %>
      <div class="genre_ranking_content_box">
        <div class="genre_ranking_content_rank">
          <%= "#{i+1}位"%>
        </div>
        <div class="genre_ranking_content_detail">
          <%= book[0] %>
        </div>
        <div class="genre_ranking_content_detail">
          <%= "#{book[1]}回" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/read_book_logs/_graph_page.html.erb
<div class="chart">
  <%= column_chart @datas , 
    id: "column-chart", 
    width: "90vw", 
    height: "70vh", 
    colors: ["#FFC107"] 
  %>
</div>

app/views/read_book_logs/book_ranking.html.erb
<div class="wrapper">
  <div class="headder">
    <%= render "books/headder" %>
  </div>
  <div class="book_ranking_page">
    <%= render "book_ranking_page" %>
  </div>
</div>

app/views/read_book_logs/genre_ranking.html.erb
<div class="wrapper">
  <div class="headder">
    <%= render "books/headder" %>
  </div>
  <div class="book_ranking_page">
    <%= render "genre_ranking_page" %>
  </div>
</div>

app/views/read_book_logs/graph.html.erb
<div class="wrapper">
  <div class="headder">
    <%= render "books/headder" %>
  </div>
  <div class="graph">
    <%= render "graph_page" %>
  </div>
</div>

app/views/read_book_logs/index.html.erb
<div class="wrapper">
  <div class="headder">
    <%= render "books/headder" %>
  </div>
  <div class="book_ranking_page">
    <%= render "book_ranking_page" %>
  </div>
</div>

app/views/toppages/_top_page_contents.erb
<div class="top_page_contents">
  <div class="book_content">
    <div class="content_image">
      <%= link_to image_tag("/images/book.png" )  , books_path  %>
      <div class="content_subject">
        <%= link_to "本棚", books_path, class: "content_name" %>
      </div>
    </div>
  </div>
  <div class="book_content">
    <div class="content_image">
      <%= link_to image_tag("/images/book.png" )  , new_book_path  %>
      <div class="content_subject">
        <%= link_to "本の登録", new_book_path, class: "content_name" %>
      </div>
    </div>
  </div>
  <div class="book_content">
    <div class="content_image">
      <%= link_to image_tag("/images/book.png" )  , new_genre_path  %>
      <div class="content_subject">
        <%= link_to new_genre_path, class: "content_name" do %>
          新規ジャンル<br>作成
        <%end%>
      </div>
    </div>
  </div>
</div>
<div class="top_page_contents">
  <div class="book_content">
    <div class="content_image">
      <%= link_to image_tag("/images/book.png" )  , root_path  %>
      <div class="content_subject">
        <%= link_to "グラフ", index_graph_path, class: "content_name" %>
      </div>
    </div>
  </div>
  <div class="book_content">
    <div class="content_image">
      <%= link_to image_tag("/images/book.png" )  , root_path  %>
      <div class="content_subject">
        <%= link_to read_book_logs_path, class: "content_name" do %>
          読んだ絵本<br>ランキング
        <% end %>
      </div>
    </div>
  </div>
  <div class="book_content">
    <div class="content_image">
      <%= link_to image_tag("/images/book.png" )  , root_path  %>
      <div class="content_subject">
        <%= link_to index_genre_ranking_path, class: "content_name" do %>
          読んだジャンル<br>ランキング
        <% end %>      
      </div>
    </div>
  </div>
</div>
<div class="trash">
   <%= link_to "ゴミ箱", trashes_box_path, class: "trash_button" %>
</div>

app/views/toppages/index.html.erb
<div class="wrapper">
  <div class="headder">
    <%= render "books/headder" %>
  </div>
  <div class="top_page">
    <%= render "top_page_contents" %>
  </div>
</div>

app/views/trashes/_trash_book_list.html.erb
<div class="trash_book_contents_line">
  <ul class="item_lists">
    <% if @books.length > 0 %>
      <% @books.each do |book| %>
        <li class="item_list">
          <div class="book_content">
            <div class="book_image">
              <img src="/images/book_cover.png" alt="絵本の表紙" title="絵本の表紙">
              <div class="book_subject">
                <%= book.book_subject %>
              </div>
              <div class="book_destroy">
                <%= link_to '復活', trash_reverse_path(book.id), method: :post %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    <% else %>
      <div class="book_content_first_time">
        <div class="book_image">
          <img src="/images/book_cover.png" alt="絵本の表紙" title="絵本の表紙">
          <div class="book_subject">
            <%= "ゴミ箱の中に" %><br>
            <%= "本はありません" %>
          </div>
        </div>
      </div>
    <% end %>
  </ul>
</div>

app/views/trashes/index.html.erb
<div class="wrapper">
  <div class="headder">
    <%= render "books/headder" %>
  </div>
  <div class="trash_book_list">
    <%= render "trash_book_list" %>
  </div>
</div>